#!/bin/bash
sudo pacman -S haveged
sudo systemctl enable haveged
sudo systemctl start haveged
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syy

sudo pacman -S chromium openbox obconf oblogout python2-xdg xfce4-terminal lxrandr lxpanel leafpad lxappearance-obconf pcmanfm networkmanager network-manager-applet lxdm xdg-user-dirs xdg-user-dirs gnome-themes-standard p7zip unzip zip unrar gtk-engine-murrine synapse wget gtk-engine-aurora synapse cantarell-fonts xarchiver xfce4-power-manager

mkdir -p ~/.config/openbox
cp -r /etc/xdg/openbox/* ~/.config/openbox

xdg-user-dirs-update
sudo updatedb

sudo systemctl enable NetworkManager
sudo systemctl enable lxdm
